#!/usr/bin/env node
/**
 * M365 Graph MCP Server — entrypoint.
 *
 * Generated by juvantlabs/juvant-tools scaffold mcp-server (via
 * juvant-tools-mcp) on 2026-05-03. Conforms to handbook
 * docs/repo-types/mcp-server.md.
 *
 * IMPORTANT: All non-protocol output must go to stderr (`console.error`).
 * Writing to stdout corrupts the MCP stdio JSON-RPC framing. CI lint
 * rules enforce this in `juvantlabs/*-mcp-server` repos.
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const LOG_LEVEL = process.env.MCP_SERVER_LOG_LEVEL ?? "info";

// Required env vars per README.md § Environment variables. CI enforces
// the README ↔ src/ env-var consistency check, so adding a documented
// env var here without wiring it (or vice versa) fails the build.
const M365_CLIENT_ID = process.env.M365_CLIENT_ID;
const M365_CLIENT_SECRET = process.env.M365_CLIENT_SECRET;
const M365_TENANT_ID = process.env.M365_TENANT_ID;

// Tenant-ID shape validation — mandated by handbook docs/repo-types/mcp-server.md
// § Conventions › Auth. Prevents arbitrary string injection into the
// authority URL during MSAL token acquisition.
const TENANT_ID_RE =
  /^(common|organizations|consumers|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;

function validateEnv(): void {
  const missing: string[] = [];
  if (!M365_CLIENT_ID) missing.push("M365_CLIENT_ID");
  if (!M365_CLIENT_SECRET) missing.push("M365_CLIENT_SECRET");
  if (!M365_TENANT_ID) missing.push("M365_TENANT_ID");
  if (missing.length > 0) {
    console.error(
      `[m365-graph-mcp-server] missing required env var(s): ${missing.join(", ")}`,
    );
    console.error(
      "[m365-graph-mcp-server] see README.md § Environment variables",
    );
    process.exit(1);
  }
  if (!TENANT_ID_RE.test(M365_TENANT_ID!)) {
    console.error(
      `[m365-graph-mcp-server] M365_TENANT_ID has invalid shape: ${M365_TENANT_ID}`,
    );
    console.error(
      "[m365-graph-mcp-server] expected: 'common' | 'organizations' | 'consumers' | <UUID>",
    );
    process.exit(1);
  }
}

const server = new Server(
  {
    name: "@juvantlabs/m365-graph-mcp-server",
    version: "0.0.1",
  },
  {
    capabilities: {
      tools: {},
    },
  },
);

// =====================================================================
// Tool list — register each tool here as it lands.
// =====================================================================
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      // {
      //   name: "m365-graph:list_drives",
      //   description: "List the user's OneDrive drives.",
      //   inputSchema: { type: "object", properties: {}, required: [] },
      // },
    ],
  };
});

// =====================================================================
// Tool dispatch — handle calls per tool name.
// =====================================================================
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name } = request.params;

  switch (name) {
    // case "m365-graph:list_drives":
    //   return await listDrives(args);

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
});

// =====================================================================
// Boot — connect to stdio and run.
// =====================================================================
async function main(): Promise<void> {
  validateEnv();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  // No stdout writes here. Server listens on stdio until the client closes.
  console.error(
    `[m365-graph-mcp-server] running on stdio (log level: ${LOG_LEVEL}, tenant: ${M365_TENANT_ID})`,
  );
}

main().catch((err) => {
  console.error("[m365-graph-mcp-server] fatal:", err);
  process.exit(1);
});
